#!/usr/bin/env bash
# KodCode Instruct-2507 CTX8K P60 Stage2, beta=0.1 Stage1 -> beta=0.1 Stage2.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RUN_PREFIX=${RUN_PREFIX:-CODE-S2-KODCODE-INSTRUCT2507-CTX8K-P60-BETA01-BETA01-V1}
export STAGE1_RUN_PREFIX=${STAGE1_RUN_PREFIX:-ONPOLICY-SFT-Qwen3-4B-INSTRUCT2507-CODE-KODCODE-CTX8K-S1-BETA01-V1}
export EXPECTED_STAGE1_RUN_PREFIX=${EXPECTED_STAGE1_RUN_PREFIX:-ONPOLICY-SFT-Qwen3-4B-INSTRUCT2507-CODE-KODCODE-CTX8K-S1-BETA01-V1}
export STAGE1_CKPT_DIR=${STAGE1_CKPT_DIR:-/data-1/checkpoints/ONPOLICY-SFT-Qwen3-4B-INSTRUCT2507-CODE-KODCODE-CTX8K-S1-BETA01-V1_1782398871}
export WDL_SFT_BETA=${WDL_SFT_BETA:-0.1}
export EXPECTED_STAGE1_BETA=${EXPECTED_STAGE1_BETA:-0.1}

export BASE_MODEL_PATH=${BASE_MODEL_PATH:-/data-1/.cache/huggingface/hub/models--Qwen--Qwen3-4B-Instruct-2507/snapshots/cdbee75f17c01a7cc42f958dc650907174af0554}
export STAGE2_HANDOFF_STEP=${STAGE2_HANDOFF_STEP:-60}
export TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-40}
export CODE_TRAIN_FILE=${CODE_TRAIN_FILE:-/data-1/dataset/code/verl_rl/kodcode_stage2_after_s1_seed20260604_beta01_p60_handoff.parquet}
export TRAIN_FILE=${TRAIN_FILE:-$CODE_TRAIN_FILE}
export MODEL2_LABEL=${MODEL2_LABEL:-kodcode_i2507_ctx8k_beta01_p60}
export MODEL2_CACHE_TAG=${MODEL2_CACHE_TAG:-kod_i2507_p60_b01_s2}
export STAGE1_MERGED_MODEL_ROOT=${STAGE1_MERGED_MODEL_ROOT:-/data-1/model_weights/code_task/kodcode_instruct2507_ctx8k_stage2_p60/beta01}

export CODE_ONLINE_HUMANEVAL_PLUS_VAL_FILE=${CODE_ONLINE_HUMANEVAL_PLUS_VAL_FILE:-/data-1/dataset/code/verl_rl/online_full_humaneval_plus/official_humaneval_plus_val.parquet}
export CODE_ONLINE_MBPP_PLUS_VAL_FILE=${CODE_ONLINE_MBPP_PLUS_VAL_FILE:-/data-1/dataset/code/verl_rl/online_full_mbpp_plus/official_mbpp_plus_val.parquet}
export CODE_ONLINE_LCB_V5_SUBSET_VAL_FILE=${CODE_ONLINE_LCB_V5_SUBSET_VAL_FILE:-/data-1/dataset/code/verl_rl/online_full_livecodebench_v5/official_livecodebench_val.parquet}
export CODE_VAL_FILES=${CODE_VAL_FILES:-"['$CODE_ONLINE_HUMANEVAL_PLUS_VAL_FILE','$CODE_ONLINE_MBPP_PLUS_VAL_FILE','$CODE_ONLINE_LCB_V5_SUBSET_VAL_FILE']"}
export TEST_FILES=${TEST_FILES:-$CODE_VAL_FILES}

export TRAIN_PROMPT_BSZ=${TRAIN_PROMPT_BSZ:-64}
export ROLLOUT_N=${ROLLOUT_N:-8}
export TRAIN_PROMPT_MINI_BSZ=${TRAIN_PROMPT_MINI_BSZ:-$((TRAIN_PROMPT_BSZ * ROLLOUT_N))}
export NGPUS_PER_NODE=${NGPUS_PER_NODE:-8}
export TRAIN_MAX_SAMPLES=${TRAIN_MAX_SAMPLES:--1}
export DATA_SEED=${DATA_SEED:-20260604}
export DATA_SHUFFLE=${DATA_SHUFFLE:-False}

export MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-1024}
export MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-4096}
export ROLLOUT_MAX_MODEL_LEN=${ROLLOUT_MAX_MODEL_LEN:-8192}
export LOG_PROB_MAX_TOKEN_LEN_PER_GPU=${LOG_PROB_MAX_TOKEN_LEN_PER_GPU:-8192}
export ROLLOUT_MAX_NUM_BATCHED_TOKENS=${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-8192}
export ACTOR_PPO_MAX_TOKEN_LEN=${ACTOR_PPO_MAX_TOKEN_LEN:-8192}

export LOSS_MODE=${LOSS_MODE:-wdl_sft}
export LR=${LR:-5e-7}
export JOINT_TRAINING_ROLLOUT_SOURCE=${JOINT_TRAINING_ROLLOUT_SOURCE:-model2}
export ROLLOUT_CALCULATE_LOG_PROBS=${ROLLOUT_CALCULATE_LOG_PROBS:-True}
export CALCULATE_ENTROPY=${CALCULATE_ENTROPY:-False}
export ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.35}
export GENERATION_MICRO_BATCH_SIZE=${GENERATION_MICRO_BATCH_SIZE:-16}
export LOG_PROB_MICRO_BATCH_SIZE=${LOG_PROB_MICRO_BATCH_SIZE:-4}

export TEST_FREQ=${TEST_FREQ:-5}
export SAVE_FREQ=${SAVE_FREQ:-10}
export VAL_N=${VAL_N:-1}
export VAL_TEMPERATURE=${VAL_TEMPERATURE:-0.2}
export VAL_TOP_P=${VAL_TOP_P:-0.95}
export VAL_BEFORE_TRAIN=${VAL_BEFORE_TRAIN:-True}
export BEST_CKPT_METRIC_KEY=${BEST_CKPT_METRIC_KEY:-"val-core/HumanEval+/acc/pass@1"}
export MAX_ACTOR_CKPTS_TO_KEEP=${MAX_ACTOR_CKPTS_TO_KEEP:-null}
export MAX_CRITIC_CKPTS_TO_KEEP=${MAX_CRITIC_CKPTS_TO_KEEP:-null}
export KEEP_BEST_CKPT=${KEEP_BEST_CKPT:-True}
export BEST_CKPT_STRIP_OPTIMIZER=${BEST_CKPT_STRIP_OPTIMIZER:-False}
export MIN_FREE_GB_FOR_CKPT=${MIN_FREE_GB_FOR_CKPT:-300}

exec bash "${SCRIPT_DIR}/run_s2_code_model2_rollout_common.sh" "$@"
