#!/usr/bin/env bash
# Common Stage1 code-task single-model On-Policy SFT launcher.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export WRAPPER_SCRIPT_DIR="$SCRIPT_DIR"

: "${RUN_PREFIX:?RUN_PREFIX must be set}"
: "${WDL_SFT_BETA:?WDL_SFT_BETA must be set}"

export INIT_MODEL_PATH=${INIT_MODEL_PATH:-"${BASE_MODEL_PATH:-/data-1/.cache/huggingface/models--Qwen--Qwen3-4B-Base/snapshots/906bfd4b4dc7f14ee4320094d8b41684abff8539}"}
export LOSS_MODE=${LOSS_MODE:-wdl_sft}
export LR=${LR:-5e-7}
export CODE_TRAIN_FILE=${CODE_TRAIN_FILE:-/data-1/dataset/code/verl_rl/kodcode_light_rl_10k_train_rl_format.parquet}
export CODE_ONLINE_HUMANEVAL_PLUS_VAL_FILE=${CODE_ONLINE_HUMANEVAL_PLUS_VAL_FILE:-/data-1/dataset/code/verl_rl/online_full_humaneval_plus/official_humaneval_plus_val.parquet}
export CODE_ONLINE_MBPP_PLUS_VAL_FILE=${CODE_ONLINE_MBPP_PLUS_VAL_FILE:-/data-1/dataset/code/verl_rl/online_full_mbpp_plus/official_mbpp_plus_val.parquet}
export CODE_ONLINE_VAL_FILE=${CODE_ONLINE_VAL_FILE:-$CODE_ONLINE_HUMANEVAL_PLUS_VAL_FILE}
export CODE_VAL_FILES=${CODE_VAL_FILES:-"['$CODE_ONLINE_HUMANEVAL_PLUS_VAL_FILE','$CODE_ONLINE_MBPP_PLUS_VAL_FILE']"}
export TRAIN_FILE=${TRAIN_FILE:-"$CODE_TRAIN_FILE"}
export TEST_FILES=${TEST_FILES:-"$CODE_VAL_FILES"}
export CUSTOM_REWARD_FN_PATH=${CUSTOM_REWARD_FN_PATH:-"${SCRIPT_DIR}/official_aligned_reward.py"}
export CUSTOM_REWARD_FN_NAME=${CUSTOM_REWARD_FN_NAME:-compute_score_code_official_aligned}
export REWARD_MANAGER=${REWARD_MANAGER:-dapo}
export CODE_EVAL_OFFICIAL_SITE=${CODE_EVAL_OFFICIAL_SITE:-/data-1/code_eval_envs/official_site}
export LCB_REPO_DIR=${LCB_REPO_DIR:-/data-1/code_eval_envs/LiveCodeBench}
export PROJECT_CACHE_ROOT=${PROJECT_CACHE_ROOT:-/data-1/.cache}
export HF_HOME=${CODE_TASK_HF_HOME:-${HF_HOME:-$PROJECT_CACHE_ROOT/huggingface}}
export HF_DATASETS_CACHE=${CODE_TASK_HF_DATASETS_CACHE:-${HF_DATASETS_CACHE:-$HF_HOME/datasets}}
export HUGGINGFACE_HUB_CACHE=${CODE_TASK_HUGGINGFACE_HUB_CACHE:-${HUGGINGFACE_HUB_CACHE:-$HF_HOME/hub}}
export TRANSFORMERS_CACHE=${CODE_TASK_TRANSFORMERS_CACHE:-${TRANSFORMERS_CACHE:-$HF_HOME}}
export XDG_CACHE_HOME=${CODE_TASK_XDG_CACHE_HOME:-${XDG_CACHE_HOME:-$PROJECT_CACHE_ROOT}}
export CODE_OFFICIAL_SOURCE_ROOT=${CODE_OFFICIAL_SOURCE_ROOT:-/data-1/dataset/code/official_sources}
export BIGCODEBENCH_OVERRIDE_PATH=${BIGCODEBENCH_OVERRIDE_PATH:-$CODE_OFFICIAL_SOURCE_ROOT/bigcodebench/BigCodeBench-v0.1.4.jsonl}
export HF_HUB_OFFLINE=${HF_HUB_OFFLINE:-1}
export HF_DATASETS_OFFLINE=${HF_DATASETS_OFFLINE:-1}
export REPO_PYTHONPATH_ROOT=${REPO_PYTHONPATH_ROOT:-/workspace/verl}
export PYTHONPATH="${REPO_PYTHONPATH_ROOT}:${CODE_EVAL_OFFICIAL_SITE}:${LCB_REPO_DIR}:${PYTHONPATH:-}"
export WANDB_PROJECT=${WANDB_PROJECT:-OnPolicyWDLSFT-CodeTask}
export WANDB_MODE=${WANDB_MODE:-offline}
export VAL_BEFORE_TRAIN=${VAL_BEFORE_TRAIN:-False}
export BEST_CKPT_METRIC_KEY=${BEST_CKPT_METRIC_KEY:-"val-core/HumanEval+/acc/pass@1"}
export BEST_CKPT_METRIC_MODE=${BEST_CKPT_METRIC_MODE:-max}
export KEEP_BEST_CKPT=${KEEP_BEST_CKPT:-True}
export MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-1024}
export MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-4096}
export TRAIN_PROMPT_BSZ=${TRAIN_PROMPT_BSZ:-8}
export ROLLOUT_N=${ROLLOUT_N:-2}
export TRAIN_PROMPT_MINI_BSZ=${TRAIN_PROMPT_MINI_BSZ:-$((TRAIN_PROMPT_BSZ * ROLLOUT_N))}
export NGPUS_PER_NODE=${NGPUS_PER_NODE:-1}
export TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-5}
export TEST_FREQ=${TEST_FREQ:-1}
export SAVE_FREQ=${SAVE_FREQ:-1}
export VAL_N=${VAL_N:-1}
export TRAIN_MAX_SAMPLES=${TRAIN_MAX_SAMPLES:-64}
export DATA_SEED=${DATA_SEED:-20260604}
export DATA_SHUFFLE=${DATA_SHUFFLE:-True}
export MIN_FREE_GB_FOR_CKPT=${MIN_FREE_GB_FOR_CKPT:-30}
export CODE_REWARD_TIMEOUT=${CODE_REWARD_TIMEOUT:-5}
export REWARD_TIMEOUT=${REWARD_TIMEOUT:-60}
export CODE_REWARD_EXEC_MAX_AS_MB=${CODE_REWARD_EXEC_MAX_AS_MB:-4096}
export BIGCODEBENCH_MAX_AS_LIMIT=${BIGCODEBENCH_MAX_AS_LIMIT:-131072}
export BIGCODEBENCH_MAX_DATA_LIMIT=${BIGCODEBENCH_MAX_DATA_LIMIT:-131072}
export BIGCODEBENCH_MAX_STACK_LIMIT=${BIGCODEBENCH_MAX_STACK_LIMIT:-10}

if [ ! -f "$TRAIN_FILE" ]; then
    if [ "${DRY_RUN:-0}" = "1" ]; then
        echo "[code-s1] WARNING: TRAIN_FILE not found during DRY_RUN: $TRAIN_FILE" >&2
    else
        echo "[code-s1] ERROR: TRAIN_FILE not found: $TRAIN_FILE" >&2
        exit 1
    fi
fi
if [ ! -f "$CUSTOM_REWARD_FN_PATH" ]; then
    echo "[code-s1] ERROR: CUSTOM_REWARD_FN_PATH not found: $CUSTOM_REWARD_FN_PATH" >&2
    exit 1
fi

print_config() {
    cat <<EOF
[CODE S1 CONFIG]
RUN_PREFIX=$RUN_PREFIX
INIT_MODEL_PATH=$INIT_MODEL_PATH
TRAIN_FILE=$TRAIN_FILE
CODE_ONLINE_HUMANEVAL_PLUS_VAL_FILE=$CODE_ONLINE_HUMANEVAL_PLUS_VAL_FILE
CODE_ONLINE_MBPP_PLUS_VAL_FILE=$CODE_ONLINE_MBPP_PLUS_VAL_FILE
CODE_ONLINE_VAL_FILE=$CODE_ONLINE_VAL_FILE
TEST_FILES=$TEST_FILES
CUSTOM_REWARD_FN_PATH=$CUSTOM_REWARD_FN_PATH
CUSTOM_REWARD_FN_NAME=$CUSTOM_REWARD_FN_NAME
REWARD_MANAGER=$REWARD_MANAGER
REPO_PYTHONPATH_ROOT=$REPO_PYTHONPATH_ROOT
CODE_EVAL_OFFICIAL_SITE=$CODE_EVAL_OFFICIAL_SITE
LCB_REPO_DIR=$LCB_REPO_DIR
PROJECT_CACHE_ROOT=$PROJECT_CACHE_ROOT
HF_HOME=$HF_HOME
HF_DATASETS_CACHE=$HF_DATASETS_CACHE
HUGGINGFACE_HUB_CACHE=$HUGGINGFACE_HUB_CACHE
XDG_CACHE_HOME=$XDG_CACHE_HOME
CODE_OFFICIAL_SOURCE_ROOT=$CODE_OFFICIAL_SOURCE_ROOT
BIGCODEBENCH_OVERRIDE_PATH=$BIGCODEBENCH_OVERRIDE_PATH
LOSS_MODE=$LOSS_MODE
WDL_SFT_BETA=$WDL_SFT_BETA
LR=$LR
TRAIN_PROMPT_BSZ=$TRAIN_PROMPT_BSZ
ROLLOUT_N=$ROLLOUT_N
TRAIN_PROMPT_MINI_BSZ=$TRAIN_PROMPT_MINI_BSZ
NGPUS_PER_NODE=$NGPUS_PER_NODE
TOTAL_TRAINING_STEPS=$TOTAL_TRAINING_STEPS
TRAIN_MAX_SAMPLES=$TRAIN_MAX_SAMPLES
DATA_SEED=$DATA_SEED
DATA_SHUFFLE=$DATA_SHUFFLE
VAL_BEFORE_TRAIN=$VAL_BEFORE_TRAIN
TEST_FREQ=$TEST_FREQ
SAVE_FREQ=$SAVE_FREQ
VAL_MAX_SAMPLES=${VAL_MAX_SAMPLES:--1}
VAL_N=$VAL_N
VAL_TEMPERATURE=${VAL_TEMPERATURE:-unset}
VAL_TOP_P=${VAL_TOP_P:-unset}
MAX_PROMPT_LENGTH=$MAX_PROMPT_LENGTH
MAX_RESPONSE_LENGTH=$MAX_RESPONSE_LENGTH
ACTOR_PPO_MAX_TOKEN_LEN=${ACTOR_PPO_MAX_TOKEN_LEN:-unset}
ACTOR_CALCULATE_ENTROPY=${ACTOR_CALCULATE_ENTROPY:-unset}
ROLLOUT_MAX_MODEL_LEN=${ROLLOUT_MAX_MODEL_LEN:-unset}
LOG_PROB_MAX_TOKEN_LEN_PER_GPU=${LOG_PROB_MAX_TOKEN_LEN_PER_GPU:-unset}
ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-unset}
ROLLOUT_MAX_NUM_BATCHED_TOKENS=${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-unset}
GENERATION_MICRO_BATCH_SIZE=${GENERATION_MICRO_BATCH_SIZE:-unset}
LOG_PROB_MICRO_BATCH_SIZE=${LOG_PROB_MICRO_BATCH_SIZE:-unset}
ROLLOUT_IS=${ROLLOUT_IS:-unset}
ROLLOUT_RS=${ROLLOUT_RS:-unset}
ROLLOUT_CALCULATE_LOG_PROBS=${ROLLOUT_CALCULATE_LOG_PROBS:-unset}
ACTOR_PPO_EPOCHS=${ACTOR_PPO_EPOCHS:-unset}
ACTOR_SHUFFLE=${ACTOR_SHUFFLE:-unset}
BEST_CKPT_METRIC_KEY=$BEST_CKPT_METRIC_KEY
BEST_CKPT_METRIC_MODE=$BEST_CKPT_METRIC_MODE
KEEP_BEST_CKPT=$KEEP_BEST_CKPT
MAX_ACTOR_CKPTS_TO_KEEP=${MAX_ACTOR_CKPTS_TO_KEEP:-unset}
MAX_CRITIC_CKPTS_TO_KEEP=${MAX_CRITIC_CKPTS_TO_KEEP:-unset}
BEST_CKPT_STRIP_OPTIMIZER=${BEST_CKPT_STRIP_OPTIMIZER:-unset}
PROTECTED_CKPT_STEPS=${PROTECTED_CKPT_STEPS:-unset}
PROTECTED_CKPT_STRIP_OPTIMIZER=${PROTECTED_CKPT_STRIP_OPTIMIZER:-unset}
BIGCODEBENCH_MAX_AS_LIMIT=$BIGCODEBENCH_MAX_AS_LIMIT
BIGCODEBENCH_MAX_DATA_LIMIT=$BIGCODEBENCH_MAX_DATA_LIMIT
CODE_REWARD_EXEC_MAX_AS_MB=$CODE_REWARD_EXEC_MAX_AS_MB
CODE_REWARD_TIMEOUT=$CODE_REWARD_TIMEOUT
CODE_REWARD_STDIN_CASE_TIMEOUT=${CODE_REWARD_STDIN_CASE_TIMEOUT:-unset}
REWARD_TIMEOUT=$REWARD_TIMEOUT
PROMPT_CONTRACT=<think>...</think><answer>\`\`\`python ... \`\`\`</answer>
BOXED_PROMPT=0
EOF
}

print_config

if [ "${DRY_RUN:-0}" = "1" ]; then
    echo "[code-s1] DRY_RUN=1; exiting before verl.trainer.main_ppo"
    exit 0
fi

# shellcheck disable=SC1091
source "${SCRIPT_DIR}/../ablation_single_model/_common_ablation.sh" \
    +ray_kwargs.ray_init.runtime_env.env_vars.CODE_REWARD_TIMEOUT="'${CODE_REWARD_TIMEOUT}'" \
    +ray_kwargs.ray_init.runtime_env.env_vars.CODE_REWARD_STDIN_CASE_TIMEOUT="'${CODE_REWARD_STDIN_CASE_TIMEOUT:-2}'" \
    +ray_kwargs.ray_init.runtime_env.env_vars.CODE_REWARD_EXEC_MAX_AS_MB="'${CODE_REWARD_EXEC_MAX_AS_MB}'" \
    +ray_kwargs.ray_init.runtime_env.env_vars.BIGCODEBENCH_MAX_AS_LIMIT="'${BIGCODEBENCH_MAX_AS_LIMIT}'" \
    +ray_kwargs.ray_init.runtime_env.env_vars.BIGCODEBENCH_MAX_DATA_LIMIT="'${BIGCODEBENCH_MAX_DATA_LIMIT}'" \
    +ray_kwargs.ray_init.runtime_env.env_vars.BIGCODEBENCH_MAX_STACK_LIMIT="'${BIGCODEBENCH_MAX_STACK_LIMIT}'" \
    data.seed=${DATA_SEED} \
    data.shuffle=${DATA_SHUFFLE} \
    "$@"
